services:
  - name: bookbuddy-backend
    type: web
    env: python
    plan: free
    branch: main
  root: backend
  buildCommand: pip install -r requirements.txt
  startCommand: "gunicorn -k uvicorn.workers.UvicornWorker -w 4 app.main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SUPABASE_URL
      - key: SUPABASE_KEY
      - key: HF_API_KEY
      - key: HF_MODEL
      - key: ALLOWED_ORIGINS
    healthCheckPath: /health
